---
title: "CCHS"
author: "Olya"
date: "2024-04-05"
output: 
  html_document:
    keep_md: true
---

## Me trying to beat the R 

Needed packages installation:
```{r setup, include=FALSE}
library("tidyverse")
library("dplyr")
```

##### Reading CCHS 2012 csv file, checking if R reads all the variables in the table as numbers
```{r}
cchs <- read_csv("/Users/olechka/Documents/R/challenges/CCHS_2012.csv")
head(cchs, 10)
sapply(cchs, class)
```

##### We checked, now creating a basic plot

```{r}
ggplot(cchs, aes(x = hwtghtm, y = hwtgwtk)) + geom_point()
```
*What an ugly plot to be honest...*

##### Making missing data become NA instead of numbers:
```{r}
cchs <- cchs %>%
  mutate(height = ifelse(hwtghtm == 9.996 | hwtghtm == 9.999, NA, hwtghtm))
cchs <- cchs %>%
  mutate(weight = ifelse(hwtgwtk == 999.96 | hwtgwtk == 999.99, NA, hwtgwtk),
         bmi = weight/height^2)
```

##### Now creating Body Mass Index categories:
```{r}
cchs <- cchs %>%
	mutate(bmi_category = case_when(
		bmi < 18.5 ~ "underweight",
		bmi >=30 & bmi <999 ~ "obese",
		bmi >=25 & bmi <30 ~ "overweight",
		bmi >=18.5 & bmi <25 ~ "normal weight",
		TRUE ~ "other"
	))
```

##### Identifying provinces' names:
```{r}
cchs <- cchs %>%
	mutate(province = case_when(
		geogprv == 10 ~ "NFLD & LAB",
		geogprv == 11 ~ "PEI",
		geogprv == 12 ~ "NOVA SCOTIA",
		geogprv == 13 ~ "NEW BRUNSWICK",
		geogprv == 24 ~ "QUEBEC",
		geogprv == 35 ~ "ONTARIO",
		geogprv == 46 ~ "MANITOBA",
		geogprv == 47 ~ "SASKATCHEWAN",
		geogprv == 48 ~ "ALBERTA",
		geogprv == 59 ~ "BRITISH COLUMBIA",
		geogprv == 60 ~ "YUKON/NWT/NUNA",
		geogprv == 96 ~ "NOT APPLICABLE",
		geogprv == 97 ~ "DON'T KNOW",
		geogprv == 98 ~ "REFUSAL",
		TRUE ~ "NOT STATED"
	))
```


Now let's plot our data:
```{r}
library(ggplot2)
scatter_clean <- ggplot(cchs, aes(x = height, y = weight)) + 
  geom_point() + 
  xlab("Height in Meters") +
  ylab("Weight in Kilograms")
plot(scatter_clean)

my_colors <- c("underweight" = "blue", "normal weight" = "darkgreen", "overweight" = "orange", "obese" = "red")
library(ggplot2)
scatter_cat <- ggplot(cchs, aes(x = height, y = weight)) + 
  geom_point(aes(colour = factor(bmi_category)), alpha = 1/5) + 
  xlab("Height in Meters") +
  ylab("Weight in Kilograms") +
  scale_color_manual(values = my_colors)
plot(scatter_cat)
```


```{r}
summarize(
  group_by(cchs, bmi_category), 
  avg_ht = mean(hwtghtm, na.rm = T), 
  sd_ht = sd(hwtghtm, na.rm = T),
  avg_wt = mean(hwtgwtk, na.rm = T), 
  sd_wt = sd(hwtgwtk, na.rm = T)
)
```
